M48
; DRILL file {KiCad 9.0.4} date 2026-01-29T23:46:10+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-29T23:46:10+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.270
%
G90
G05
T1
X196.925Y-87.3
X196.925Y-91.7
T2
X194.54Y-62.5
X194.54Y-74.5
M30
